[package]
name = "mktheme"
version.workspace = true
authors.workspace = true
edition = "2024"

[[bin]]
name = "mktheme"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
crossterm.workspace = true
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
themelib = { path = "../themelib", features = ["image"] }
toml.workspace = true
