[package]
name = "components"
edition = "2024"
authors.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
js-sys.workspace = true
leptos = { workspace = true, features = ["csr"] }
leptos-use.workspace = true
rand.workspace = true
themelib = { path = "../themelib" }
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
    "Blob",
    "BlobPropertyBag",
    "File",
    "FileList",
    "FileReader",
    "HtmlInputElement",
    "HtmlElement",
    "Element",
    "CssStyleDeclaration",
    "Url",
] }
