name = "Arcane"
version = "3.0.0"
author = "Jonathon Cobb"
variants = ["Dawn", "Dusk", "Noon", "Night"]
cool_range = [243, 177]
warm_range = [-23, 43]
offset = 0.0
lum_range = [8, 96]
lum_alpha = 1.1
lum_gamma = 1.05
muted_sat_range = [10, 25]
base_sat_range = [55, 65]
intense_sat_range = [80, 90]
