name = "Dungeoneer"
version = "3.0.0"
author = "Jonathon Cobb"
variants = ["Dawn", "Dusk", "Noon", "Night"]
cool_range = [285, 135]
warm_range = [90, 30]
offset = 0.0
lum_range = [10, 94]
lum_power = 1.1
lum_gamma = 1.1
muted_sat_range = [10, 15]
base_sat_range = [65, 80]
intense_sat_range = [88, 96]
