name = "Intrepid"
version = "3.0.0"
author = "Jonathon Cobb"
variants = ["Dawn", "Dusk", "Noon", "Night"]
cool_range = [217, 283]
warm_range = [123, 57]
offset = 0.0
lum_range = [10, 94]
lum_power = 1.0
lum_gamma = 1.0
muted_sat_range = [10, 25]
base_sat_range = [55, 65]
intense_sat_range = [80, 90]
