[package]
name = "themelib"
version.workspace = true
authors.workspace = true
edition = "2024"

[lib]
name = "themelib"
path = "src/lib.rs"

[[bin]]
name = "mktheme"
path = "src/main.rs"
required-features = ["image"]

[features]
default = []
image = ["dep:image"]

[dependencies]
anyhow.workspace = true
byteorder.workspace = true
clap = { workspace = true, features = ["derive"] }
crossterm.workspace = true
glam.workspace = true
image = { workspace = true, optional = true, features = [
    "jpeg",
    "png",
    "webp",
] }
itertools.workspace = true
lazy_static.workspace = true
regex.workspace = true
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
toml.workspace = true
